/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2022-02-24 10:52:48
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <stdarg.h>
#include <string.h>
#include "argparse.h"

static enum argparse_option_t last_parsed_option;
static char last_error_message[256];
static const char *option_texts[] = {
	[ARG_FIRMWARE] = "-f / --firmware",
	[ARG_TRACECNT] = "-n / --tracecnt",
	[ARG_KEY] = "-k / --key",
	[ARG_OUTPUT_DIRECTORY] = "output_directory",
};

enum argparse_option_internal_t {
	ARG_FIRMWARE_SHORT = 'f',
	ARG_TRACECNT_SHORT = 'n',
	ARG_KEY_SHORT = 'k',
	ARG_FIRMWARE_LONG = 1000,
	ARG_TRACECNT_LONG = 1001,
	ARG_KEY_LONG = 1002,
	ARG_OUTPUT_DIRECTORY_LONG = 1003,
};

static void errmsg_callback(const char *errmsg, ...) {
	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

static void errmsg_option_callback(enum argparse_option_t error_option, const char *errmsg, ...) {
	last_parsed_option = error_option;

	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

bool argparse_parse(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	last_parsed_option = ARGPARSE_NO_OPTION;
	const char *short_options = "f:n:k:";
	struct option long_options[] = {
		{ "firmware",                         required_argument, 0, ARG_FIRMWARE_LONG },
		{ "tracecnt",                         required_argument, 0, ARG_TRACECNT_LONG },
		{ "key",                              required_argument, 0, ARG_KEY_LONG },
		{ "output_directory",                 required_argument, 0, ARG_OUTPUT_DIRECTORY_LONG },
		{ 0 }
	};

	while (true) {
		int optval = getopt_long(argc, argv, short_options, long_options, NULL);
		if (optval == -1) {
			break;
		}
		last_error_message[0] = 0;
		enum argparse_option_internal_t arg = (enum argparse_option_internal_t)optval;
		switch (arg) {
			case ARG_FIRMWARE_SHORT:
			case ARG_FIRMWARE_LONG:
				last_parsed_option = ARG_FIRMWARE;
				if (!argument_callback(ARG_FIRMWARE, optarg, errmsg_callback)) {
					return false;
				}
				break;

			case ARG_TRACECNT_SHORT:
			case ARG_TRACECNT_LONG:
				last_parsed_option = ARG_TRACECNT;
				if (!argument_callback(ARG_TRACECNT, optarg, errmsg_callback)) {
					return false;
				}
				break;

			case ARG_KEY_SHORT:
			case ARG_KEY_LONG:
				last_parsed_option = ARG_KEY;
				if (!argument_callback(ARG_KEY, optarg, errmsg_callback)) {
					return false;
				}
				break;

			default:
				last_parsed_option = ARGPARSE_NO_OPTION;
				errmsg_callback("unrecognized option supplied");
				return false;
		}
	}

	const int positional_argument_cnt = argc - optind;
	last_parsed_option = ARGPARSE_POSITIONAL_ARG;
	if (positional_argument_cnt != 1) {
		errmsg_callback("expected exactly 1 positional argument, but %d given.", positional_argument_cnt);
		return false;
	}

	int positional_index = optind;
	last_parsed_option = ARG_OUTPUT_DIRECTORY;
	if (!argument_callback(ARG_OUTPUT_DIRECTORY, argv[positional_index++], errmsg_callback)) {
		return false;
	}

	if (plausibilization_callback) {
		if (!plausibilization_callback(errmsg_option_callback)) {
			return false;
		}
	}
	return true;
}

void argparse_show_syntax(void) {
	fprintf(stderr, "usage: trace_simulator [-f filename] [-n count] [-k key] path\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "Emulates embedded code and simulates power traces.\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "positional arguments:\n");
	fprintf(stderr, "  path                  Output directory to write tracefiles into.\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "optional arguments:\n");
	fprintf(stderr, "  -f filename, --firmware filename\n");
	fprintf(stderr, "                        The firmware file to emulate. Defaults to aes128_rom.bin.\n");
	fprintf(stderr, "  -n count, --tracecnt count\n");
	fprintf(stderr, "                        An integer that specifies the amount of traces to generate by default.\n");
	fprintf(stderr, "                        Defaults to 1000.\n");
	fprintf(stderr, "  -k key, --key key     Gives the key to feed the implementation. By default the key is entirely\n");
	fprintf(stderr, "                        zeros.\n");
}

void argparse_parse_or_quit(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	if (!argparse_parse(argc, argv, argument_callback, plausibilization_callback)) {
		if (last_parsed_option > ARGPARSE_POSITIONAL_ARG) {
			if (last_error_message[0]) {
				fprintf(stderr, "trace_simulator: error parsing argument %s -- %s\n", option_texts[last_parsed_option], last_error_message);
			} else {
				fprintf(stderr, "trace_simulator: error parsing argument %s -- no details available\n", option_texts[last_parsed_option]);
			}
		} else if (last_parsed_option == ARGPARSE_POSITIONAL_ARG) {
			fprintf(stderr, "trace_simulator: error parsing optional arguments -- %s\n", last_error_message);
		}
		argparse_show_syntax();
		exit(EXIT_FAILURE);
	}
}

#ifdef __ARGPARSE_MAIN__
/*   gcc -D __ARGPARSE_MAIN__ -O2 -Wall -o argparse argparse.c
*/

static const char *option_enum_to_str(enum argparse_option_t option) {
	switch (option) {
		case ARG_FIRMWARE: return "ARG_FIRMWARE";
		case ARG_TRACECNT: return "ARG_TRACECNT";
		case ARG_KEY: return "ARG_KEY";
		case ARG_OUTPUT_DIRECTORY: return "ARG_OUTPUT_DIRECTORY";
	}
	return "UNKNOWN";
}

bool arg_print_callback(enum argparse_option_t option, const char *value, argparse_errmsg_callback_t errmsg_callback) {
	fprintf(stderr, "%s = \"%s\"\n", option_enum_to_str(option), value);
	return true;
}

int main(int argc, char **argv) {
	argparse_parse_or_quit(argc, argv, arg_print_callback, NULL);
	return 0;
}
#endif
